// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetSecure.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetSecure.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212174554_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetSecure.Api.Models.AclRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DestinationVlanId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SourceVlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AclRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "PERMITIR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Admin acceso total a DMZ",
                            DestinationVlanId = 99,
                            Priority = 1,
                            Protocol = "ANY",
                            SourceVlanId = 10
                        },
                        new
                        {
                            Id = 2,
                            Action = "PERMITIR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ventas acceso Web a DMZ",
                            DestinationVlanId = 99,
                            Priority = 2,
                            Protocol = "TCP",
                            SourceVlanId = 20
                        },
                        new
                        {
                            Id = 3,
                            Action = "BLOQUEAR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IoT no puede acceder a Admin",
                            DestinationVlanId = 10,
                            Priority = 3,
                            Protocol = "ANY",
                            SourceVlanId = 30
                        });
                });

            modelBuilder.Entity("NetSecure.Api.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VlanId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ip = "192.168.10.5",
                            Name = "Admin-PC-01",
                            Type = "PC",
                            VlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ip = "192.168.10.10",
                            Name = "Admin-Srv",
                            Type = "SERVER",
                            VlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ip = "192.168.20.5",
                            Name = "Ventas-Laptop",
                            Type = "PC",
                            VlanId = 2
                        },
                        new
                        {
                            Id = 4,
                            Ip = "192.168.30.15",
                            Name = "Cam-Frontal",
                            Type = "IOT",
                            VlanId = 3
                        },
                        new
                        {
                            Id = 5,
                            Ip = "172.16.1.5",
                            Name = "WebServer",
                            Type = "SERVER",
                            VlanId = 4
                        });
                });

            modelBuilder.Entity("NetSecure.Api.Models.TrafficLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationDevice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DestinationVlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceDevice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceVlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("TrafficLogs");
                });

            modelBuilder.Entity("NetSecure.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$D1HaR75k6pj6riZMp9rPSut5QAJUUTb7PgLloblA74sz7osAG7de.",
                            Role = "admin",
                            Username = "CENV"
                        });
                });

            modelBuilder.Entity("NetSecure.Api.Models.Vlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subnet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VlanId")
                        .IsUnique();

                    b.ToTable("Vlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "bg-emerald-600",
                            Name = "Administración",
                            Subnet = "192.168.10.0/24",
                            VlanId = 10
                        },
                        new
                        {
                            Id = 2,
                            Color = "bg-blue-600",
                            Name = "Ventas",
                            Subnet = "192.168.20.0/24",
                            VlanId = 20
                        },
                        new
                        {
                            Id = 3,
                            Color = "bg-orange-600",
                            Name = "IoT / Cámaras",
                            Subnet = "192.168.30.0/24",
                            VlanId = 30
                        },
                        new
                        {
                            Id = 4,
                            Color = "bg-purple-600",
                            Name = "Servidores DMZ",
                            Subnet = "172.16.1.0/24",
                            VlanId = 99
                        });
                });

            modelBuilder.Entity("NetSecure.Api.Models.Device", b =>
                {
                    b.HasOne("NetSecure.Api.Models.Vlan", "Vlan")
                        .WithMany("Devices")
                        .HasForeignKey("VlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vlan");
                });

            modelBuilder.Entity("NetSecure.Api.Models.TrafficLog", b =>
                {
                    b.HasOne("NetSecure.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetSecure.Api.Models.Vlan", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
